/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.farmacio.ui;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import org.farmacia.domain.Cliente;
import org.farmacia.domain.Usuario;
import org.farmacia.services.ClienteService;
import org.farmacia.services.UsuarioService;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author ZaidaPT
 */
public class UIBuscarCliente extends javax.swing.JInternalFrame {
    private ApplicationContext applicationContext;
    private UIPedido uIPedido;
    /**
     * Creates new form UIBuscarCliente
     */
    public UIBuscarCliente(ApplicationContext applicationContext,UIPedido uIPedido) {
        this.applicationContext = applicationContext;
        this.uIPedido = uIPedido;
        initComponents();
        
        this.uIPedido.setVisible(false);
        
        listarClientes();
    }

    private void listarClientes(){
        ClienteService clienteService = applicationContext.getBean("clienteService",ClienteService.class);
        List<Cliente> clientes = clienteService.listar();

        TableModel tableModel = new TableModel(clientes);
        
        jTable1.setModel(tableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));
        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Ingrese Dato:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/farmacia/ui/iconos/Buscar.gif"))); // NOI18N
        jButton1.setText("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Selecciones Modo de Búsqueda:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private class TableModel extends AbstractTableModel{
        private String[] headers = {"Nombre"
                         ,"Apellidos"
                         ,"Direccion"
                         ,"DNI"
                         };
        private List<Cliente> data;

        public TableModel(List<Cliente> data){
            this.data = data ;
        }
		
        @Override
        public int getColumnCount() {
                return this.headers.length;
        }

        @Override
        public int getRowCount() {
                return this.data.size();
        }

        @Override
        public Object getValueAt(int fila, int columna) {
                Object obj = null;
                Cliente cliente = data.get(fila);

                switch(columna){
                    case 0:
                        obj = cliente.getNombre();
                        break;
                    case 1:
                        obj = cliente.getApellido();
                        break;  
                    case 2:
                        obj = cliente.getDireccion();
                        break;
                    case 3:
                        obj = cliente.getDni();
                        break;
                }
                return obj;
        }
		
        @Override
        public String getColumnName(int column) {
                return this.headers[column];
        }	

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
                return columnIndex==4;
        }
		
        public void filterData(List data){
                this.data = data;
                fireTableStructureChanged();
        }
    }
}
