/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.farmacio.ui;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import org.farmacia.domain.Laboratorio;
import org.farmacia.services.LaboratorioService;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author ZaidaPT
 */
public class UIListarLaboratorios extends javax.swing.JInternalFrame {
    private ApplicationContext applicationContext;
    /**
     * Creates new form UIListarProvincias
     */
    public UIListarLaboratorios(ApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
        initComponents();
        listarLaboratorios();
    }
    
    private void listarLaboratorios(){
        LaboratorioService laboratorioService = applicationContext.getBean("laboratorioService",LaboratorioService.class);
        List<Laboratorio> provincias = laboratorioService.listar();
        
        TableModel tableModel = new TableModel(provincias);
        
        jTable1.setModel(tableModel);
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Provincias"));
        setClosable(true);
        setMaximizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private class TableModel extends AbstractTableModel{
        private String[] headers = {"Nombre"

                         };
        private List<Laboratorio> data;

        public TableModel(List data){
            this.data = data ;
        }
		
        @Override
        public int getColumnCount() {
                return this.headers.length;
        }

        @Override
        public int getRowCount() {
            return this.data.size();
        }

        @Override
        public Object getValueAt(int fila, int columna) {
            return data.get(fila).getNombre();
        }
		
        @Override
        public String getColumnName(int column) {
            return this.headers[column];
        }
		
        public void filterData(List data){
            this.data = data;
            fireTableStructureChanged();
        }
    }
}
